apiVersion: v1
kind: DataProduct
metadata:
  name: 
  catalogName: 
  schemaName: 
  dataDomainName: 
  summary: 
  description: |
owners:
  - name: #Alice Johnson
    email: #alice.johnson@example.com
relevantLinks:
  - label: # Documentation
    url: # https://docs.example.com
tags:
#  - analytics
sampleQueries:
  - name: 
    description: 
    query: |
  - name: 
    query: 
views:
  - name:
    description: 
    viewSecurityMode: DEFINER
    definitionQuery: |
    columns:
      - name: 
        type: 
        description: 
  - name: 
    description: 
    viewSecurityMode: INVOKER
    definitionQuery: |
    columns:
      - name: 
        type: 
        description: 
materializedViews:
  - name: 
    description: 
    definitionQuery: |
    definitionProperties:
      grace_period:
      incremental_column:
      refresh_interval: 
      storage_schema: 
    columns:
      - name:
        type: 
        description:
  - name: 
    description: 
    definitionQuery: |
    definitionProperties:
      refresh_schedule: 
      storage_schema: 
    columns:
      - name: 
        type: 
        description: 
exportMetadata:
  exportedAt: 
  exportedBy: 
  status: 
  createdAt: 
  publishedAt: 